package org.cakelab.glsl.pp.tokens;

import org.cakelab.glsl.Interval;
import org.cakelab.glsl.lang.ast.impl.NodeImpl;

/** base class of all tokens generated by the preprocessor */
public abstract class Token extends NodeImpl {
	protected String text;
	
	public Token(Interval interval, String text) {
		super(interval);
		this.text = text;
	}

	public Token(Token that) {
		super(that);
		this.text = that.text;
	}

	public Token(String text) {
		this.text = text;
	}

	public String getText() {
		return text;
	}

	public int length() {
		return text.length();
	}
	
	public String toString() {
		return text;
	}
	
	public abstract Token clone();

	
}
