package org.cakelab.glsl.pp;

import org.cakelab.glsl.Location;
import org.cakelab.glsl.pp.ast.MacroInvocation;

/**
 * Location of a token generated by a macro expansion.
 * <p>
 * The actual location attributes (source identifier, line and column) 
 * refer to the location (start) of the macro invocation in the original 
 * text (before expansion).
 * </p>
 * <p>{@link #getMacroInvocation()} provides the AST entry of the 
 * macro invocation which has been expanded during preprocessing.
 * </p>
 * <p>
 * {@link #getMacroExpandedOffset()} additionally provides 
 * the position of the generated token in the macro expanded text, 
 * relative to the start of the expanded text. This may be useful
 * to point out error in expanded text rather than just pointing 
 * to the malicious macro invocation or definition.
 * </p>
 * 
 * <h3>Note:</h3> Start and end of a token or expression can be 
 *              inside macro expanded or simple text sections (e.g. 
 *              it can start in a text location and end in a 
 *              macro expanded location).
 *              
 * @author homac
 *
 */
public class MacroExpandedLocation extends Location {

	private int macroExpandedOffset;
	private MacroInvocation invocation;

	// TODO check whether we can drop some of the constructors
	public MacroExpandedLocation(Location that, int macroExpandedOffset, MacroInvocation macroInvocation) {
		super(that);
		this.macroExpandedOffset = macroExpandedOffset;
		this.invocation = macroInvocation;
	}

	public MacroExpandedLocation(MacroExpandedLocation that) {
		super(that);
		this.macroExpandedOffset = that.macroExpandedOffset;
		this.invocation = that.invocation;
	}

	public MacroExpandedLocation(MacroInvocation macroInvocation) {
		super(macroInvocation.getStart());
		this.macroExpandedOffset = LexerLocation.POS_START;
		this.invocation = macroInvocation;
	}

	public int getMacroExpandedOffset() {
		return macroExpandedOffset;
	}

	public MacroInvocation getMacroInvocation() {
		return invocation;
	}
	
	@Override
	public int getLexerPosition() {
		return macroExpandedOffset;
	}

	@Override
	protected void nextLine() {
		nextColumn();
	}

	@Override
	protected void nextColumn() {
		macroExpandedOffset++;
	}

	@Override
	protected void setLexerPosition(int lastConsumedPos) {
		macroExpandedOffset = lastConsumedPos;
	}
	
	
	
}
