package org.cakelab.glsl.pp;

import org.cakelab.glsl.Location;
import org.cakelab.glsl.pp.ast.MacroInvocation;

/**
 * Location of an input token generated by a macro expansion.
 * <p>
 * The location attributes (source identifier, line and column) 
 * refer to the location (start) of the macro invocation in the
 * input text. In case this input text was produced by macro expansion
 * as well, the location will point to the start of that macro invocation.
 * Thus, location always points to the start of the first macro 
 * invocation in the original input, which interfered with the
 * macro invocation of the macro expanded text parsed for this
 * location.
 * </p>
 * <p>{@link #getMacroInvocation()} provides the AST entry of the 
 * macro invocation which has been expanded during preprocessing.
 * If this macro invocation is based on another macro invocation,
 * the start (and end eventually) will be a macro expanded location
 * as well, which has a reference of that macro invocation.
 * </p>
 * <p>
 * {@link #getMacroExpandedOffset()} additionally provides 
 * the position of the generated token in the macro expanded text, 
 * relative to the start of the expanded text. This may be useful
 * to point out errors in expanded text rather than just pointing 
 * to the malicious macro invocation or definition.
 * </p>
 * 
 * <h3>Note:</h3> Start and end of a token or expression can be 
 *              inside macro expanded or simple text sections (e.g. 
 *              it can start in a text location and end in a 
 *              macro expanded location).
 *              
 * @author homac
 *
 */
public class MacroExpandedLocation extends Location {
	
	private MacroInvocation invocation;

	public MacroExpandedLocation(MacroExpandedLocation that) {
		super(that);
		this.invocation = that.invocation;
	}

	/** 
	 * Creates a macro expanded location, pointing at the start
	 * of the expanded text of the given macro invocation expression.
	 * 
	 * @param macroInvocation
	 */
	public MacroExpandedLocation(MacroInvocation macroInvocation) {
		super("");
		this.invocation = macroInvocation;
	}

	public MacroExpandedLocation(MacroInvocation invocation, Location originalLocation) {
		super(originalLocation);
		this.invocation = invocation;
	}

	public MacroInvocation getMacroInvocation() {
		return invocation;
	}

	public MacroExpandedLocation clone() {
		return new MacroExpandedLocation(this);
	}
	
}
